ARG NODE_VERSION=14.20.0
FROM node:${NODE_VERSION}-alpine3.16

WORKDIR /var/www/courselab/frontend

#COPY package*.json ./

RUN npm install

RUN npm cache clean -f
RUN npm cache verify
RUN npm install -g react-scripts
#RUN npm audit fix

#COPY docker-entrypoint.sh /usr/local/bin/
#RUN chmod +x /usr/local/bin/docker-entrypoint.sh
#ENTRYPOINT ["docker-entrypoint.sh"]
